import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomSidebar from "@/components/Sidebar/CustomSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-stone-50`}>
        <CustomSidebar />
        <div className="p-4 sm:ml-32">
          <div className="p-2">
            Global
          </div>
          <div className='p-7'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
