export interface SubscriptionViewModel {
    id:string,
    name:string,
    description?:string | null,
    quantity:number,
    unitPrice:number,
    total:number,
    anniversaryDate:string | Date,
    servicePeriodStartAt:string | Date,
    servicePeriodEndAt:string | Date,
    activationDate:string | Date,
    isAutomaticRenewal:boolean,
    paymentCycle:string,
    subscriptionCycle:string,
    status:string,
    createdAt:string | Date,
    createdBy:string,
    updatedAt?:string | Date | null,
    updatedBy?:string | null,

    productId:string,
    productName:string,
    productVendor:string,
    productManufacturer:string,
    productGroupName:string,
    productTypeName:string

    pendingOrderId?:string,
    pendingOrderNumber?:string,
}